version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/v8"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/vendor"
    schedule:
      interval: "daily"