# Simple workflow for deploying static content to GitHub Pages
name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - '20'
          - '18'

    runs-on: ${{ matrix.os }}

    name: Test Node ${{ matrix.node-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: ''
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run test
        env:
          FORCE_COLOR: true