name: Test PR

on:

  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ''

      - run: npm install
      - run: npm run build
      - run: npm run test-pr
        env:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: true
          
